### ISSUE TITLE
package ‘phanghorn’ is not available (for R version 3.0.3)

### ISSUE THREAD

**Issue by attilacsordas** [KlausVigo/shinyTreeViewer#1]
when trying to run shinyTreeViewer I get this above, is this issue expected and if yes, can be fixed easily?

**Comment by Drsatterfield** [comment]
Hi I am having the same issue as above using r version 4.0.2, if you have any advice that would be helpful. Thanks in advance.

**Comment by EronDS** [comment]
same problem with different version sof r(4.0,3,5,3.4)
Any solutions?

**Comment by KlausVigo** [comment]
Hi @Drsatterfield, @EronDS, 
try installing phangorn `install.packages("phangorn")` beforehand. 
Regards, 
Klaus

**Comment by AKOUNDA** [comment]
Salut, 
j'ai un problème pour installer le package "pharngon" sur mon R.4.0.2
voici le message d'erreur
Warning in install.packages :
  package ‘phangorn’ is not available (for R version 4.0.2)
avez vous des conseils pour moi?

**Comment by Prash7596** [comment]
Hi,
I have the same issue:

"Warning in install.packages :
  package ‘phangorn’ is not available (for R version 4.0.2)"

Any suggestions?
